### ISSUE TITLE
still have a plan to release the code and data for training and testing

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [TencentARC/DeSRA#1]

**Comment by LiangbinXie** [comment]
Yes, we will release the code and data within this month. The code is currently under internal review by the company.

**Comment by sanbuphy** [comment]
> Yes, we will release the code and data within this month. The code is currently under internal review by the company.

wait for the cool code

**Comment by HikariDawn777** [comment]
> > Yes, we will release the code and data within this month. The code is currently under internal review by the company.
> 
> wait for the cool code

Same here!

**Comment by LiangbinXie** [comment]
Sorry for the delay, the codes and data have been prepared, please stay tuned!

**Comment by wangxinchao-bit** [comment]
wait for the codes hopefully

**Comment by YLongJin** [comment]
May I ask when the planned event will be released

**Comment by 201210302** [comment]
I'm waiting... looking forward to your code... 👍

**Comment by LiangbinXie** [comment]
Due to the accumulation of many tasks and the lengthy internal review process within the company, the open sourcing has been delayed for a long time. Thank you for your attention. I have just open-sourced our code for detecting Artifacts and the dataset we proposed.

**Comment by LiangbinXie** [comment]
I will close this issue now. If there are any other issues, don't hesitate to open a new one.

**Comment by 201210302** [comment]
Thank you for your response:)👍👍
-----Original Message-----
