### ISSUE TITLE
No module in mmseg

### ISSUE THREAD

**Issue by Explore008** [TencentARC/DeSRA#3]
Hello,there is a issue have generated in your coding''from mmseg.apis import inference_segmentor, init_segmentor, show_seg
from mmseg.core.evaluation import get_palette'', because the mmseg do not have this files. I have check all method in mmseg files,these package do not exist.
secondly, How to use your script/artifact_dection to clear the Artifact in my own image generated by another GAN?
Thank you very much!(The demo to clear one image)
![4df0a0310c22c34edefa35c9c6645cf](https://github.com/TencentARC/DeSRA/assets/111834651/8ecf3694-f316-4b68-ad11-5bc23e446150)
![ea798067d1c7f8bf0940a99cfea5447](https://github.com/TencentARC/DeSRA/assets/111834651/d194ab8c-2cdd-4044-9356-236e38ee8992)

**Comment by LiangbinXie** [comment]
The version of mmsegmentation and mmcv-full that used in the experiment are 0.29.0 and 1.6.1, respectively. The mmsegmentation package has a major update this year.

**Comment by LiangbinXie** [comment]
For detecting the artifacts generated by another GAN, you should also get the corresponding results of MSE-based model. Then you can use the artifact_detection.py script.

**Comment by Explore008** [comment]
> The version of mmsegmentation and mmcv-full that used in the experiment are 0.29.0 and 1.6.1, respectively. The mmsegmentation package has a major update this year.

Sorry, I tested the installation of mmcv on three servers. No matter which version of mmcv it is, it is incompatible and the required packages cannot be imported. I tested 1.13.1+cu11.6.2. 0.1+cu11.8 uses mmcv1.6.1 1.7.0 2.0.0rc4, all of which have the following error: AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc4.
Or is there any better tool code I can use? mmcv is really difficult to use

**Comment by LiangbinXie** [comment]
You should also check the version of mmsegmentation.
