### ISSUE TITLE
FileNotFoundError: checkpoints/segformer_mit-b5_640x640_160k_ade20k_20220617_203542-940a6bd8.pth can not be found.

### ISSUE THREAD

**Issue by Solaris34** [TencentARC/DeSRA#4]
请问checkpoints文件在哪下载？

**Comment by LiangbinXie** [comment]
mmsegmentation上面

**Comment by LiangbinXie** [comment]
进入这个link：https://github.com/open-mmlab/mmsegmentation/tree/main/configs/segformer，
然后挑选对应的checkpoint。也并不一定必须是需要使用某个checkpoint的segformer，对应的最好，因为其它的我们也没有试过。

**Comment by Explore008** [comment]
> 请问checkpoints文件在哪下载？

hello,have you solve this problem? I have try to download this checkpoints in mmseg0.29.0,but got this error 'File "/root/autodl-tmp/mmseg/mmseg/apis/inference.py", line 35, in init_segmentor
    model.CLASSES = checkpoint['meta']['CLASSES']
KeyError: 'meta'' whatever choose anyone! thank you!

**Comment by haikunzhang95** [comment]
> 进入这个link：[https://github.com/open-mmlab/mmsegmentation/tree/main/configs/segformer，](https://github.com/open-mmlab/mmsegmentation/tree/main/configs/segformer%EF%BC%8C) 然后挑选对应的checkpoint。也并不一定必须是需要使用某个checkpoint的segformer，对应的最好，因为其它的我们也没有试过。

页面已经不存在了。

**Comment by LiangbinXie** [comment]
[https://github.com/open-mmlab/mmsegmentation/tree/main/configs/segformer](https://github.com/open-mmlab/mmsegmentation/tree/main/configs/segformer)
