### ISSUE TITLE
About MSE model

### ISSUE THREAD

**Issue by Explore008** [TencentARC/DeSRA#6]
Which MSE model do you use? I didn't find this model in the paper. Is it EDSR or SRResnet?
Thank you for your reply！

**Comment by LiangbinXie** [comment]
For Real-ESRGAN and LDL, we adopt the RealESRNet as the MSE model. Because these two GAN-based models are both fine-tuned from the Real-ESRNet model.

For SwinIR, we trained the MSE model based on the SwinIR setting ourselves, and then added the GAN loss to fine-tune based on this MSE model.

I will provide the models adopted in the paper.

**Comment by Explore008** [comment]
> 对于Real-ESRGAN和LDL，我们采用RealESRNet作为MSE模型。因为这两个基于 GAN 的模型都是从 Real-ESRNet 模型微调而来的。
> 
> 对于 SwinIR，我们自己根据 SwinIR 设置训练了 MSE 模型，然后添加了 GAN 损失以基于此 MSE 模型进行微调。
> 
> 我将提供本文中采用的模型。

Thank you very much! When load the checkpoints in mmseg0.29.0,I have got this problem"model.CLASSES = checkpoint['meta']['CLASSES']
KeyError: 'meta'".This checkpoints is true？
![0ab16f5f78fb5006ced51a8a6b7cf00](https://github.com/TencentARC/DeSRA/assets/111834651/61ef8e56-7c16-4f1b-a22d-e8447a64780a)

**Comment by LiangbinXie** [comment]
I just uploaded the checkpoints to Google Drive, you can get them from this link (https://drive.google.com/drive/folders/10vzKAJjHm5GEb0_LESnHYmuCnBwdoFpm). The corresponding information has also been updated on the project homepage.

**Comment by cncloudli** [comment]
> For Real-ESRGAN and LDL, we adopt the RealESRNet as the MSE model. Because these two GAN-based models are both fine-tuned from the Real-ESRNet model.
> 
> For SwinIR, we trained the MSE model based on the SwinIR setting ourselves, and then added the GAN loss to fine-tune based on this MSE model.
> 
> I will provide the models adopted in the paper.

有一点我不太理解，RealESRGAN的论文里写Real-ESRNet用的是L1 LOSS，为什么这里说他是MSE（L2 LOSS）的模型呢？谢谢！
