### ISSUE TITLE
Is lables losed?

### ISSUE THREAD

**Issue by Explore008** [TencentARC/DeSRA#7]
Hello, I tried to reproduce your results, but after correcting many problems, it still only completed the mask segmentation and showed that the array was out of bounds when loading the category. Is this problem caused by an error in the class name in the class?
“ File "demo/artifact_detection.py", line 131, in main
    label_name = CLASSES[label]
IndexError: list index out of range”
Can you create a colab demo in your project？Thank you！

**Comment by nnmaitian** [comment]
Hello, I encountered the following problem, from mmseg.apis import inference_segmentor, init_segmentor, show_seg
ImportError: cannot import name 'inference_segmentor' from 'mmseg.apis' . How to solve it.

**Comment by LiangbinXie** [comment]
@Explore008 Did you follow the specific version of mmsegmentation?

**Comment by haikunzhang95** [comment]
> Hello, I tried to reproduce your results, but after correcting many problems, it still only completed the mask segmentation and showed that the array was out of bounds when loading the category. Is this problem caused by an error in the class name in the class? “ File "demo/artifact_detection.py", line 131, in main label_name = CLASSES[label] IndexError: list index out of range” Can you create a colab demo in your project？Thank you！

Did you solve the error? I had the same error.

**Comment by BhJia** [comment]
I also encounter the error, did you solve it?

**Comment by AaANNYYAaA** [comment]
@Explore008 @haikunzhang95 

I also encountered the error, did you solve it?

**Comment by LiangbinXie** [comment]
I suspect that the version of mmsegmentation in your environment is not consistent with the version specified in the README. If this is the case, you can refer to issue #9
