### ISSUE TITLE
How to make "GT-Mask", "DeSRA-Mask"??

### ISSUE THREAD

**Issue by 201210302** [TencentARC/DeSRA#8]
Hello, I would like to apply a new image to DeSRA. I know how to create GAN-SR and MSE-SR images, but I don't know how to create GT-Mask and DeSRA-Mask images. I would be very grateful if you could explain. :)

**Comment by LiangbinXie** [comment]
The GT-Mask images are manually labeled (by the LabelMe tool). The DeSRA-Mask images are generated by the artifact_detection.py (https://github.com/TencentARC/DeSRA/blob/main/scripts/artifact_detection.py) script.
